site_name: Timothy's Website
site_url: https://bailitaotao.com
theme:
  name: material
  logo: assets/images/logo-tao-no-frame.svg
  favicon: assets/images/logo-tao-no-frame.svg
  palette:
    primary: white 
  features:
    - navigation.tabs
    - navigation.path
    - navigation.top
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Bailitaotao
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@bailitaotao
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/325680073
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bailitaotao/
  generator: false


extra_css:
  - stylesheets/extra.css

copyright: Copyright &copy; 2024 - 2025 Timothy Tao

